# Generated by Django 3.2.9 on 2022-06-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=300, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('link', models.CharField(max_length=300, verbose_name='ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portals')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Новости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news')),
            ],
        ),
        migrations.CreateModel(
            name='NewTechno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='new_techno')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, verbose_name='Название партнера')),
                ('partner_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners_images', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Полное описание')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='first.projects')),
            ],
        ),
        migrations.CreateModel(
            name='FullDescriptionNewTechno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст_новых_технологий')),
                ('techno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_techno_description', to='first.newtechno')),
            ],
        ),
        migrations.CreateModel(
            name='FullDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_descriptions', to='first.news')),
            ],
        ),
        migrations.CreateModel(
            name='EmDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='first.employee')),
            ],
        ),
    ]
