# Generated by Django 3.2.9 on 2022-06-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtechno',
            name='date',
        ),
        migrations.RemoveField(
            model_name='newtechno',
            name='title',
        ),
        migrations.AddField(
            model_name='newtechno',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newtechno',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='newtechno',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images', verbose_name='Фото'),
        ),
    ]
