# Generated by Django 3.2.9 on 2022-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_portfoliocompanies'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalCongresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='international', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Полное описание')),
            ],
        ),
    ]
