# Generated by Django 3.2.9 on 2022-06-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20220603_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='full_name',
        ),
    ]
