# Generated by Django 3.2.9 on 2022-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20220623_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Должность'),
        ),
    ]
