# Generated by Django 3.2.9 on 2022-06-07 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Новости'),
        ),
        migrations.CreateModel(
            name='Fulldescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_descriptions', to='first.news')),
            ],
        ),
    ]
