# Generated by Django 3.2.9 on 2022-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20220623_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtechno',
            name='project_title_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newtechno',
            name='project_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newtechno',
            name='text_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Поле'),
        ),
        migrations.AddField(
            model_name='newtechno',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Поле'),
        ),
    ]
