# Generated by Django 3.2.9 on 2022-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20220623_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_name_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
