# Generated by Django 3.2.9 on 2022-06-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20220609_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(blank=True, upload_to='partners_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='partner_description',
            field=models.TextField(blank=True),
        ),
    ]
