# Generated by Django 3.2.9 on 2022-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_auto_20220612_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newtechno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, null=True)),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='portfolio_images', verbose_name='Фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='education',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio_images', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
