# Generated by Django 3.2.9 on 2022-06-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_newsimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagersQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='managers', verbose_name='Фото')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
