# Generated by Django 3.2.9 on 2022-06-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_managersquotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='managersquotes',
            name='job_title_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='managersquotes',
            name='job_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='managersquotes',
            name='text_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='managersquotes',
            name='text_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
