# Generated by Django 3.2.9 on 2022-07-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_rezultatyoblastey_videocontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sotrudniki',
            new_name='Employee',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'Сотрудники'},
        ),
    ]
