# Generated by Django 3.2.9 on 2022-07-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_auto_20220706_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proekty',
            new_name='Projects',
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['project_title'], 'verbose_name': 'Портфолио'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['project_name'], 'verbose_name': 'Проекты'},
        ),
    ]
