# Generated by Django 3.2.9 on 2022-07-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_auto_20220706_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='smi',
            options={'ordering': ['title'], 'verbose_name': 'СМИ о нас'},
        ),
    ]
