# Generated by Django 3.2.9 on 2022-07-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0021_auto_20220706_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TchitatyMenedzherov',
            new_name='ManagersQuotes',
        ),
        migrations.AlterModelOptions(
            name='managersquotes',
            options={'ordering': ['full_name'], 'verbose_name': 'Цитаты менеджеров'},
        ),
        migrations.AlterModelOptions(
            name='rezultatyoblastey',
            options={'verbose_name': 'Результаты областей'},
        ),
        migrations.AlterModelOptions(
            name='videocontent',
            options={'verbose_name': 'Видео контент'},
        ),
    ]
