# Generated by Django 3.2.9 on 2022-07-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0022_auto_20220706_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulldescription',
            options={'verbose_name': 'Полное описание новостей'},
        ),
    ]
